export const arr = [{ a: 'Motivation', b: require('../assets/Images/motivation.jpg'), color: 'red' },
{ a: 'Love', b: require('../assets/Images/love.jpg'), color: 'lightblue' },
{ a: 'Money', b: require('../assets/Images/money.jpg') }, {
    a: 'Health',
    b: require('../assets/Images/health.jpg')
},
{ a: 'Travel', b: require('../assets/Images/travel.jpg') },
{ a: 'Letting go', b: require('../assets/Images/letsgo.jpg') },
{ a: 'Confidence / self esteem', b: require('../assets/Images/confidence.jpg') },
{ a: 'Relationships', b: require('../assets/Images/relationships.jpg') }]

export const Generalaffirmation = [{
    name: 'GENERAL', values: ['I am thankful for waking up this morning and treat it like the gift that it is.',
        'I am open to receive all things that will propel me closer to my dream',
        'I ask for guidance in times of trouble and trust that the universe will see me through',
        'I choose my words carefully to manifest on purpose',
        'I choose to look for the good in every situation. If there’s bad, there must be good',
        'I am raising my vibration to match the frequency of my dream.',
        'I believe in myself which causes me to change my life.',
        'I have a great attitude which aids me in all that I do.',
        'I am open to receive blessings and prosper',
        'Things are always working out for me.',
        'I am thankful for the universe for allowing me to create anything I want.',
        'I am moving forward with confidence',
        'I appreciate all that life has to offer.',
        'I am unlearning behaviours that no longer serve me and replace them with  behaviours that I can benefit from.',
        'I listen to my intuition to move me forward',
        'I take time to reflect on things to seek better ways that they can be done.',
        'I make decisions quickly without thinking about finances. I decide based on my desire to do the thing. Anything is possible.',
        ' I am grateful for all that I have so I will attract more things to be grateful for.',
        'I am aware of my vibration and adjust it accordingly when needed.',
        'I remain focused on each task until it is complete. ',
        'I am grateful for the ideas that flow to me and act on them accordingly.',
        'I look within to make changes in my life.',
        'I help people and inspire them to make positive changes in their lives.',
        'I affirm things that I want to see in my material world.',
        'I am free to be myself and am accepted for who I am by others.',
        'I help others without any expectation.',
        ' I am grateful for my wonderful and abundant life.',
        'I choose to live in the present moment        ',
        'I am committed to grow spiritually',
        'The words I speak are in alignment with my goals.',
        'I work when I want, where I want and with who I want',
        'I am co-creating with the universe.',
        'Happiness is my Birth right so being happy comes easily to me']
},
{
    name: 'MONEY', values: [
        'All the money in the world is available to me.',
        'Im so happy and grateful for all the money I have and all the money that’s on its way',
        'I am a money magnet as I have a positive relationship with money',
        'Money flows to me constantly from all over the world',
        'I earn money as I sleep from multiple different sources',
        ' I am a successful entrepreneur and my business keeps on growing as each day passes',
        'I am deserving of wealth, abundance and riches',
        'I am attracted to money and money is attracted to me.',
        'I have a money mindset and expect money to flow to me effortlessly so it does.',
        'I have enough money to buy all that I want or need.',
        'I have enough money to buy all that I want or need.        ',
        'My money continuously grows so I can help others in need.',
        'I stay humble as my wealth increases',
        'I can handle success with grace.',
        'My finances improve beyond my wildest dreams.',
        'New ideas flow to me easily which contributes to my multiple sources of income',
        'I am increasing the service I provide to others and my finances improve because of this.',
        'I constantly attract opportunities that create more money',
        'My bank account never stops growing.',
        ' I am so happy and grateful now that I have multiple sources of income that increases        daily.',
    ]
},
{
    name: 'HEALTH', values: [
        'I am so happy and grateful for my healthy mind, body and soul.',
        'My health keeps on improving with every breath that I take.',
        'I am in perfect health.',
        'I am grateful for my health, strength and vitality.',
        'I am always full of energy so I can accomplish all that I have set out to do.',
        'I give myself the care and attention that I deserve. ',
        'I make good choices that benefit my health.',
        'I focus on my blessing to attract more blessings to me.',
        'I distance myself from any negativity and instead choose to pour positivity into my        mind, body and soul.',
        'I have faith that the universe will deliver me what I need or something better',
        'I am so happy and grateful that I have perfect health and feel revitalised',
        'I stop worry about things that are out of my control.',
    ]

}, {
    name: 'LOVE', values: [
        'I am grateful for all the love and happiness I receive daily.',
        'I am attracting a kind and loving partner who accepts me for who I am.',
        'I am deserving of love.',
        'I see and experience love in everything I do.',
        'I attract loving and affection people into my life.',
        'I am vibrating at the frequency of love.',
        'I am enough.',
        'I am a joy to be around.',
        'I love myself unconditionally which pours over into everything I do.        ',
        ' I welcome love and romance into my life.',
        'I give love and it is returned to me X10.',
        ' I am grateful for all the love that surrounds me.',
        'My partner and I have a wonderful relationship that just gets better and better.  ',
        'I attract positive like-minded friends who inspire me to grow.        ',
        'My relationship with family and friends are in perfect harmony.',
        'I am so happy and grateful for my joyous perfect harmony relationship with my life partner.',
    ]
}, {
    name: 'FORGIVENESS', values: [
        'I forgive myself for dwelling on circumstances that were out of my control. Instead,',
        'I welcome abundance in all areas of my life.',
        'I am forgiving all those people that I felt done me wrong and choose to send them',
        'I let go of everything that no longer serves me.',
        'I practice forgiving daily and level up in the process',
        'I am free from all limiting beliefs',
        'I make room for the good that I desire by letting go of anything that isn’t in        alignment with my higher self.',
        'I let things go at the end of each day to welcome new blessings tomorrow',
        'Forgiveness starts with me.',
        'I focus on the future and let go of the past',

    ]
}, {
    name: 'MOTIVATION', values: [
        'I attract opportunities and people that are in alignment with my goals and my  journey of positivity.',
        'I trust in the process and know that the universe will send me all that I need in perfect timing.',
        'I have the power to change my life by changing my thoughts.',
        'I am committed to my goals and I know that I will achieve them.',
        'I have the power to create a successful business.',
        '. I choose to work in harmony with the universe and create my life on purpose.        ',
        'I am deserving of a life full of luxury.        ',
        'I can find comfort in being uncomfortable as this allows me to grow,',
        'Challenges are opportunities for me to grow. I am committed to learn each lesson and apply what I have learnt to my life.',
        'What I seek is also seeking me. I am seeking happiness, health and wealth',
        'I take action to achieve my goals.        ',
        'I am always improving all areas of my life',
        'I am ready to take a quantum leap.        ',
        'I am manifesting the life of my dreams.',
        'I believe I can so I will        ',
        'I set goals that challenge me and causes me to grow.',
        'I take risks and ignore common sense.',
        'I am moving forward with confidence.',
        'I am persistent even during times of adversity. What I seek is on the other side of adversity and persistence will get me through.',
        'I use my imagination to create what I want in mind so I experience it in my physical world.',
        'I am unlimited',
    ]
}]